#:schema https://rlbot.org/schemas/match.json
[rlbot]
launcher = "NoLaunch"
auto_start_agents = true
wait_for_agents = true

[match]
game_mode = "Soccer"
game_map_upk = "Stadium_P"
skip_replays = false
start_without_countdown = false
existing_match_behavior = "Restart"
enable_rendering = false
enable_state_setting = true
auto_save_replay = false
freeplay = false

[mutators]
match_length = "Unlimited"
max_score = "Unlimited"
overtime = "Unlimited"
series_length = "Unlimited"
game_speed = "Default"
boost_amount = "NormalBoost"

[[cars]]
config_file = "ChadGPT.bot.toml"
team = "Blue"

[[cars]]
config_file = "ChadGPT.bot.toml"
team = "Blue"

[[cars]]
config_file = "ChadGPT.bot.toml"
team = "Blue"

[[cars]]
config_file = "ChadGPT.bot.toml"
team = "Orange"

[[cars]]
config_file = "ChadGPT.bot.toml"
team = "Orange"

[[cars]]
config_file = "ChadGPT.bot.toml"
team = "Orange"
